MyStor.EndPoints.WebUI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using MyStor.Core.Contracts.Orders;
using MyStor.Core.Domain.Carts;
using MyStor.Core.Domain.Orders;

namespace MyStor.EndPoints.WebUI.Controllers
{
    public class OrderController : Controller
    {
        private OrderRepository repository;
        private Cart cart;

        public OrderController(OrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout()
        {
            return View(new Order());
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed), new {Id = order.OrderId});
            }
            else
            {
                return View(order);
            }
        }

        public IActionResult Completed(int id)
        {
            var order = repository.Find(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

    }
}

MyStor.EndPoints.WebUI/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using MyStor.Core.Contracts.Orders;
using MyStor.Core.Contracts.Payments;
using MyStor.Core.Domain.Payments;

namespace MyStor.EndPoints.WebUI.Controllers
{
    public class PaymentController : Controller
    {
        private readonly OrderRepository orderRepository;
        private readonly PaymentService payment;
        private readonly IConfiguration configuration;

        public PaymentController(OrderRepository repository, PaymentService payment, IConfiguration configuration)
        {
            this.orderRepository = repository;
            this.payment = payment;
            this.configuration = configuration;
        }

        [HttpPost]
        public IActionResult RequestPayment(int orderId)
        {
            var order = orderRepository.Find(orderId);
            var result = payment.RequestPayment(order.lines.Sum(c => c.Product.Price).ToString(), "09122345677", order.OrderId.ToString(), $"Description {order.Name}", "6104256545891236");
            if(result.IsCorrect)
            {
                orderRepository.SetTransactionId(orderId, result.Token);
                return Redirect($"{configuration["PayIr:PaymentUrl"]}{result.Token}");
            }
            return View(result);
        }

        public IActionResult Verify(RequestPaymentRsult result)
        {
            if (result.IsCorrect)
            {
                var verifyResult = payment.VerifyPayment(result.Token.ToString());
                if (verifyResult.IsCorrect)
                {
                    orderRepository.SetPaymentDone(verifyResult.factorNumber);
                    return View("PaymentComplete", verifyResult);
                }
            }
            return View(result);
        }
    }
}

MyStor.EndPoints.WebUI/Views/Order/Checkout.cshtml
@model Order
<h2>Check Out Now</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-action="Checkout" asp-controller="Order" method="post">
    <h3>Ship To</h3>
    <div class="form-group">
        <label>Name:</label><input asp-for="Name" class="form-control" />
    </div>
    <h3>Address</h3>
    <div class="form-group">
        <label>Line 1:</label><input asp-for="Line1" class="form-control" />
    </div>
    <div class="form-group">
        <label>Line 2:</label><input asp-for="Line2" class="form-control" />
    </div>
    <div class="form-group">
        <label>Line 3:</label><input asp-for="Line3" class="form-control" />
    </div>
    <div class="form-group">
        <label>City:</label><input asp-for="City" class="form-control" />
    </div>
    <div class="form-group">
        <label>State:</label><input asp-for="State" class="form-control" />
    </div>
    <div class="form-group">
        <label>Zip:</label><input asp-for="Zip" class="form-control" />
    </div>
    <div class="form-group">
        <label>Country:</label><input asp-for="Country" class="form-control" />
    </div>
    <h3>Options</h3>
    <div class="checkbox">
        <label>
            <input asp-for="GiftWrap" /> Gifr Wrap these Items
         </label>
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete Order" />
    </div>
</form>

MyStor.EndPoints.WebUI/Views/Order/Completed.cshtml
@model Order

@{
    ViewData["Title"] = "Completed";
}

<h2>Completed</h2>
<table>
    <tr>
        <td>OrderId</td>
        <td>@Model.OrderId</td>
    </tr>
    <tr>
        <td>Price</td>
        <td>@Model.lines.Sum(c => c.Product.Price)</td>
    </tr>
</table>

<form asp-controller="Payment" asp-action="RequestPayment" method="post">
    <input type="hidden" name="orderId" value="@Model.OrderId" />
    <input type="submit" value="Complete" />
</form>